version: '3'
services:
  registry:
    image: registry:2
    ports:
      - "5005:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - /Users/singaravelannandakumar/go/src/awesomeProject3/docker-registry/data:/data
      - /Users/singaravelannandakumar/go/src/awesomeProject3/docker-registry/data/auth:/auth